adfinis/customer-center

Makefile
From npm 5.x on, npm cache is healing itself and a cache clean is not
neccessary anymore
=> Makefile: remove npm cache clean

tools/docker/ucs/Dockerfile
4.2 currently breaks the installation script
=> lock the UCS version to 4.1.3

backend/src/login/index.js
This was forgotten when we moved to a JS-based config.
=> Make ldapCustomer camelcase instead of snake case

frontend/app/components/dashboard-rt/component.js, frontend/app/dashboard/template.hbs, frontend/app/notfound/template.hbs, frontend/mirage/config.js
This reverts commit 5f8ddb6418d7119b418abb64926014fd9d3218fc, reversing
changes made to c6b822e805851670e35adf206fd4a9a7ff28158b.
We will still need the statistics param in the backend due to performace problems.
=> Revert "Merge pull request #96 from velrest/fix-dashboard-route"

backend/src/timed/proxy.js, backend/src/utils/sentry.js
the email field in `userData` is sadly not searchable since its just a JSON string. We now set it separately as a tag which allows us in sentry to filter by email.
=> feat(sentry): make email field searchable in sentry

frontend/app/models/timed-subscription-project.js
This problem was reported through Sentry.
=> fix: filter non-existant orders

frontend/app/styles/components/nav-breadcrumbs.scss, frontend/app/ui/components/nav-breadcrumbs/template.hbs
This makes the breadcrumbs shorter. Plus, the home
route is only a redirect anyway. Not something I want
to give real-estate to.
=> feat(frontend): make breadcrumbs home an icon

frontend/app/services/timed.js, frontend/app/styles/app.scss, frontend/app/ui/subscriptions/detail/controller.js, frontend/app/ui/subscriptions/detail/template.hbs, frontend/tests/unit/ui/subscriptions/detail/controller-test.js
Depends on #144 
To limit the initial requests. Additionally, this
updates the markup to have orders and reports
side-by-side on larger viewports.
=> feat(frontend): add load-more to detail page

frontend/translations/en.yaml
Depends on #146 
Reload doesn't make too much sense from a user's perspective.
=> fix(frontend): rename "Reload" to "Recharge"

frontend/app/services/timed.js, frontend/app/ui/subscriptions/reload/controller.js, frontend/app/ui/subscriptions/reload/template.hbs, frontend/translations/de.yaml, frontend/translations/en.yaml
The form is only shown to admins who should have the ability
to manually set the date.
=> feat(frontend): add date field to reload form

frontend/app/helpers/format-duration-short.js, frontend/app/styles/app.scss, frontend/app/styles/pages/subscriptions/list.scss, frontend/app/ui/subscriptions/list/controller.js, frontend/app/ui/subscriptions/list/template.hbs, frontend/package.json, frontend/translations/de.yaml, frontend/translations/en.yaml, frontend/yarn.lock
This list is needed by backoffice and sales and is currently
manually copy/pasted into their tool of choice.
=> feat(frontend): add CSV export for the subscription list

frontend/app/ui/subscriptions/reload/controller.js, frontend/app/ui/subscriptions/reload/template.hbs
So 1.25 hours and 5 minutes are added as 1 hour and 20 minutes.
=> feat(frontend): allow hours as floats when reloading subscriptions

frontend/config/environment.js
This doesn't work with the current setup as the Timed API doesn't
send the required CSP headers. If we want to measure performance
of the Customer Center we need to update the Timed backend.
=> fix(frontend): disable Sentry performance measurement

frontend/app/ui/subscriptions/list/controller.js
Another proxy that will not return the expected value otherwise.
=> fix(frontend): use the getter instead of bracket notation

frontend/app/ui/subscriptions/confirm/template.hbs, frontend/app/ui/subscriptions/list/controller.js, frontend/app/ui/subscriptions/list/template.hbs
With the values in production it makes more sense to have the
customer name first. Even if the focus is on the project.
=> fix(frontend): update order or project and customer columns

frontend/app/ui/components/data-table/heading-search/component.js, frontend/app/ui/subscriptions/list/controller.js, frontend/app/ui/subscriptions/list/template.hbs, frontend/tests/integration/ui/components/data-table/heading-search/component-test.js
Currently, a second search ignores the first but doesn't update
the corresponding UI element. This update now allows for searches
to be used together.
The sorting is still somewhat broken but that will be fixed later.
=> fix(frontend): fix problem where different searches would conflict

frontend/app/ui/components/project-info/template.hbs, frontend/tests/integration/helpers/format-duration-short-test.js, frontend/tests/integration/helpers/format-duration-test.js, frontend/tests/integration/ui/components/nav-breadcrumbs/component-test.js, frontend/tests/integration/ui/components/project-info/component-test.js, frontend/tests/integration/ui/components/status-battery/component-test.js
This adds tests for both duration helpers and updates the tests for
the breadcrumbs and project-info components.
=> feat(frontend): add more automated tests

frontend/app/styles/components/status-battery.scss
The 50px are currently correct but this should not use absolute values.
=> fix(frontend): make battery height relative

frontend/app/ui/components/data-table/heading-sort/component.js, frontend/app/ui/components/status-battery/component.js
For now, these only list the available arguments of the component.
I will add types and descriptions later.
=> docs(frontend): add doc-comments to remaining components

frontend/app/services/notify.js, frontend/app/ui/application/template.hbs
Setting the timeout as a property on the extending class
is no longer possible with the native class syntax.
=> fix(frontend): update closeAfter setting

frontend/app/ui/subscriptions/confirm/controller.js, frontend/translations/de.yaml, frontend/translations/en.yaml
Currently, it is hard-coded to use the hours which leads to ugly
number when confirming minutes. This change uses `.humanize()`
with the user's current locale.
Closes #180
=> fix(frontend): use the correct time unit in confirmation dialogs

frontend/app/styles/pages/subscriptions/list.scss
This adds a margin and inline-block to improve wrapping.
=> fix(frontend): add spacing and improve wrapping of export button

.github/workflows/test.yml
No need to keep using version 10 here.
=> fix(frontend): update Node version used in GitHub Actions

frontend/app/services/account.js, frontend/app/ui/application/controller.js, frontend/app/ui/application/template.hbs, frontend/app/ui/subscriptions/confirm/route.js, frontend/app/ui/subscriptions/detail/controller.js, frontend/app/ui/subscriptions/detail/template.hbs, frontend/app/ui/subscriptions/index/route.js, frontend/app/ui/subscriptions/list/route.js, frontend/app/ui/subscriptions/own/controller.js, frontend/app/ui/subscriptions/own/route.js, frontend/app/ui/subscriptions/own/template.hbs, frontend/app/ui/subscriptions/reload/controller.js, frontend/app/ui/subscriptions/reload/route.js, frontend/app/ui/subscriptions/reload/template.hbs, frontend/config/environment.js
I chose a simple isAdmin/isCustomer model and didn't realize that
this will not work to implement the previous requirements. This
change drops the isWhatever and instead introduces methods to
check if the user is in one or multiple groups. This is in essence
the system we had before.
Closes #179
=> fix(frontend): correct the required access rights

.github/workflows/test.yml, README.md
Seems I forgot to remove them when copying an existing workflow.
But, as this is a project we only test with a lockfile.
=> fix(frontend): remove floating dependency tests

frontend/app/adapters/application.js, frontend/app/routes/-authenticated.js, frontend/app/ui/account/login/route.js, frontend/app/ui/account/password-confirm/route.js, frontend/app/ui/error/controller.js, frontend/app/ui/error/template.hbs, frontend/app/ui/subscriptions/confirm/route.js, frontend/app/ui/subscriptions/list/route.js, frontend/app/ui/subscriptions/reload/route.js, frontend/config/environment.js, frontend/package.json, frontend/tests/unit/ui/error/controller-test.js, frontend/yarn.lock
This also includes some other improvements related to the session
handling. The main fix is to check for UnauthorizedError in a new
error action of the -authenticated route.
```js
@action error(error, transition) {
if (error instanceof UnauthorizedError) {
this.transitionTo("account.login");
return false;
}
return true;
}
```
Fixes #187
=> fix(frontend): redirect on 401 instead of showing error

.gitignore, .vscode/launch.json, README.md, backend/package.json
Because the console is a terrible way to debug an environment :smile:
=> feat(backend): add debugger configurations

.github/workflows/release-container-image.yaml
PR branches should not login into ghcr.io, as forks don't work because the PAT isn't shared with them. Which is good. 
There is really no need to login, as we just want to test the build of the image.
=> fix(release-container-image.yaml): do not login on pr

README.md
The configuration is now rather straight forward for anyone who
previously worked with Docker containers. What would be nice is
a description for every configuration option. This can now be done
through Convict but it would be a major undertaking.
=> docs: remove obsolete section about the configuration

frontend/app/application/controller.js
If the logout is performed on the application level only, the server
will still hold a valid token and therefore perform a login right
after the logout, resulting in not being able to log out from the
application.
=> fix(oidc): perform logout on the server

frontend/app/components/project-info/template.hbs, frontend/app/subscriptions/list/template.hbs, frontend/app/subscriptions/own/template.hbs, frontend/translations/de.yaml, frontend/translations/en.yaml
The remaining time has been displayed as total time until now and
that is wrong. There is the `ordered time`, which is the total
duration of placed orders and there is the `remaining time`, which
is (`ordered time` - `reported time`).
=> fix(translations): rename total to remaining

frontend/app/subscriptions/reload/controller.js, frontend/app/transforms/django-duration.js
The backend expects the duration of a subscription package in the
format `HH:mm:ss`. Our  previous implementation failed if the
duration exceeded 24 hours.
For instance, if the duration was 30 hours, it was given in the
format `DD HH:mm:ss` which the backend did not expect. Now, the
calculation of total hours is done manually and not via Moment.js,
as there is not a feasible solution for `DD HH:mm:ss` -> `HH:mm:ss`.
Furthermore, the transform has been updated to not throw an error
when serializing a non-moment-duration value.
=> fix(subscription/reload): calculate total hours manually

frontend/app/services/timed.js, frontend/app/subscriptions/detail/controller.js, frontend/app/subscriptions/detail/template.hbs, frontend/app/subscriptions/own/controller.js, frontend/app/subscriptions/own/template.hbs, frontend/app/subscriptions/reload/route.js, frontend/translations/de.yaml, frontend/translations/en.yaml
Customers shouldn't be able to reload subscriptions directly.
Show an info banner for customer in project-detail.
=> fix(subscriptions): remove reload button for customers

frontend/package.json
Dependabot errored cause of non available user for the repo.
=> chore: update maintainers block

frontend/Dockerfile
Follow up from #414
Missed the `node` image for container building.
=> ci(builder): bump node version to 18
