adfinis/customer-center

backend/config.json.example
backend/src/login/index.js

Signed-off-by: Christian Zosel <christian.zosel@adfinis-sygroup.ch>

support second ldap endpoint for login

---

.eslintrc.json
backend/gulpfile.js
backend/migrations/20170711083058_remove_vault_metadata.js
backend/package-lock.json
backend/package.json
backend/src/app.js
backend/src/password-reset.js
backend/src/redmine/redmine-proxy.js
backend/src/rt/rt-proxy.js
backend/src/services.js
backend/src/symon/symon-proxy.js
backend/src/timescout/timescout-proxy.js
backend/src/vault/vault-proxy.js
frontend/app/components/input-or-show/template.hbs
frontend/app/components/vault-tree-filter/component.js
frontend/app/helpers/nl2br.js
frontend/app/redmine/service.js
frontend/app/symon/service/model.js
frontend/app/timescout/abo/route.js
frontend/app/vault/service.js
frontend/bower.json
frontend/config/environment.js
frontend/package.json

Add autolinking for vault secrets

---

README.md
tools/docker/vault/scripts/init.sh
tools/docker/vault/scripts/my-policy.hcl

Create a new policy that allows our dummy users to see secrets.

Fix vault setup

---

frontend/app/styles/app.css

After adding the small delay, I couldn't reproduce the bug where the navigation isn't showed when logging in.

Small delay in animation

---

frontend/app/components/crud-list-item/component.js
frontend/app/components/crud-list-item/template.hbs
frontend/app/components/crud-list/component.js
frontend/app/components/crud-list/template.hbs
frontend/app/components/input-or-show/component.js
frontend/app/components/input-or-show/template.hbs
frontend/app/locales/de/translations.js
frontend/app/locales/en/translations.js
frontend/tests/integration/components/crud-list-item/component-test.js

password is not visible per default
add cancel button to form

vault password listing improvement

---

backend/src/app.js
backend/src/login/index.js

and some minor bugfixes for local dev env, fixes #30

Don't log entire error object when vault login fails

---

backend/config.example.js
backend/src/login/index.js

Make vault auth backend configurable

---

frontend/app/index/template.hbs
frontend/app/locales/de/translations.js
frontend/app/locales/en/translations.js

I used the german "Wegbeschreibung" also in the english version. Or would you rather leave out the link completely when using the english version?

Update outdated service list, hide nonexistent integrations

---

backend/config.example.js
backend/knexfile.js

fix knex db migrations

---

.prettierrc
.travis.yml

see https://github.com/emberjs/ember.js/issues/15641

limit travis to 2 jobs

---

backend/src/app.js
backend/src/login/index.js
frontend/app/login/route.js
frontend/app/services/ajax.js
frontend/package-lock.json
frontend/package.json

And some other minor auth-related fixes

Refactor login: log out after 401 is received

---

Makefile
README.md

I don't like to execute three commands when I can do it with one instead.
I'm not sure if knex-migrations is the right target name but it will work. 
The name can easily be changed :)

make DB Migrations using a simple make target

---

README.md
backend/config-dev.js
backend/config.example.js
frontend/config/environment.js
frontend/tests/acceptance/dashboard-test.js

replace example config with useable dev config

refactor(config): remove rt and gitlab from frontend

---

frontend/app/locales/de/translations.js
frontend/app/locales/en/translations.js
frontend/app/timed-admin/detail/controller.js
frontend/app/timed-admin/detail/route.js
frontend/app/timed-admin/detail/template.hbs

feat(frontend): pageinate reports on timed-admin/detail

---

backend/src/timed/proxy.js

Previously we just reported an error if the requested permission does not exist on the route.

fix(sentry): actually report info if user has no access

---

backend/src/login/index.js
backend/src/timed/proxy.js
backend/src/timed/token.js
docker-compose.yml

fix authentication to match v0.13

fix(timed): change authentication to match new system

---

frontend/app/pods/dashboard/template.hbs

update address of zurich office

---

Makefile
backend/app/router.js
backend/app/routes/auth/helpers.js
backend/app/routes/auth/routes.js
backend/app/routes/services/routes.js
frontend/config/environment.js
provisioning/vault/scripts/init.sh

Reverts adfinis-sygroup/customer-center#136
Vault is not needed in the Customer Center anymore and can be disabled.

Revert "fix(services): Enable vault in production"

---

backend/config-dev.js
docker-compose.yml

Depends on #139 
Update the config to use the MailHog service.

fix: update SMTP config for dev

---

backend/app/routes/auth/routes.js

Depends on #140 
Token is set on this same line. Not sure where this came from.

 fix: remove undeclared variable

---

backend/package.json

Depends on #141
The maintainers field is interesting for developers and
the author field adds some branding for the company.

chore: add the author and maintainers fields

---

frontend/app/styles/components/status-battery.scss
frontend/app/ui/components/status-battery/component.js
frontend/app/ui/components/status-battery/template.hbs
frontend/app/ui/index/template.hbs

Depends on #145 
* Use warning-status from model instead of own.
* Fix styling

fix(frontend): update status-battery

---

frontend/app/styles/pages/index.scss
frontend/app/styles/pages/subscriptions/own.scss
frontend/app/styles/pages/subscriptions/reload.scss

Depends on #147 
Especially, when viewing through a screenshare the cards
tend to blur with the background.

fix(frontend): add more contrast to cards

---

frontend/app/styles/pages/index.scss
frontend/app/styles/pages/subscriptions/own.scss
frontend/app/styles/pages/subscriptions/reload.scss
frontend/app/ui/subscriptions/confirm/template.hbs

Depends on #148 
Having the linked project as the first column looks better.

fix(frontend): update order in confirmation table 

---

frontend/app/styles/components/project-info.scss
frontend/app/styles/pages/index.scss
frontend/app/styles/pages/subscriptions/own.scss
frontend/app/styles/pages/subscriptions/reload.scss
frontend/app/ui/components/project-info/template.hbs
frontend/app/ui/index/template.hbs
frontend/app/ui/subscriptions/confirm/template.hbs
frontend/app/ui/subscriptions/own/template.hbs
frontend/app/ui/subscriptions/reload/template.hbs

Depends on #149 
They might not be perfect but should suffice for now.

feat(frontend): add breakpoints to various elements

---

frontend/app/styles/components/project-info.scss
frontend/app/styles/pages/index.scss
frontend/app/styles/pages/subscriptions/own.scss
frontend/app/styles/pages/subscriptions/reload.scss
frontend/app/ui/components/project-info/template.hbs
frontend/app/ui/index/template.hbs
frontend/app/ui/subscriptions/confirm/template.hbs
frontend/app/ui/subscriptions/detail/controller.js
frontend/app/ui/subscriptions/own/template.hbs
frontend/app/ui/subscriptions/reload/template.hbs

Depends on #150 
This looks better and gives more information.

feat(frontend): use project name in breadcrumbs

---

frontend/app/services/timed.js
frontend/app/styles/components/project-info.scss
frontend/app/styles/pages/index.scss
frontend/app/styles/pages/subscriptions/own.scss
frontend/app/styles/pages/subscriptions/reload.scss
frontend/app/ui/components/project-info/template.hbs
frontend/app/ui/index/template.hbs
frontend/app/ui/subscriptions/confirm/template.hbs
frontend/app/ui/subscriptions/detail/controller.js
frontend/app/ui/subscriptions/own/template.hbs
frontend/app/ui/subscriptions/reload/template.hbs

Depends on #151 
The original idea was to use the UIkit slider. But that didn't work
so now we try and see how people react to two lines of projects.

feat(frontend): increase projects on dashboard to 4 

---

frontend/app/services/timed.js
frontend/app/styles/components/project-info.scss
frontend/app/styles/pages/index.scss
frontend/app/styles/pages/subscriptions/own.scss
frontend/app/styles/pages/subscriptions/reload.scss
frontend/app/ui/components/project-info/template.hbs
frontend/app/ui/index/route.js
frontend/app/ui/index/template.hbs
frontend/app/ui/subscriptions/confirm/template.hbs
frontend/app/ui/subscriptions/detail/controller.js
frontend/app/ui/subscriptions/own/template.hbs
frontend/app/ui/subscriptions/reload/template.hbs

Depends on #152 
Because the old list was... old.

 feat(frontend): add new Adfinis locations to dashboard 

---

frontend/app/ui/application/controller.js

Depends on #153 
The language change is now handled in the account service.

fix(frontend): remove obsolete code

---

frontend/app/styles/components/project-info.scss
frontend/app/ui/application/controller.js

Depends on #154 
The 10px border was too thick and the background didn't work well either.
This adds a thin, colored line and a dashed, gray line around the info.

feat(frontend): update project-info design

---

frontend/tests/unit/ui/application/controller-test.js
frontend/translations/de.yaml

As the application has reached a rather stable state I decided
to reintroduce the German translations.

feat(frontend): add German translations

---

frontend/app/services/timed.js

Depends on #155 
findAll triggers requests to non-existant endpoints.

fix(frontend): omit failing JSON:API requests 

---

frontend/app/services/timed.js
frontend/app/styles/app.scss
frontend/app/styles/pages/subscriptions/reload.scss
frontend/config/ember-intl.js

fix(frontend): minor (scss) fixes

---

frontend/translations/de.yaml

This one I missed and stumbled upon it during the presentation...

feat(frontend): add missing German translation

---

README.md
provisioning/init.sh

This adds a Bash script that executes all the provisioing commands
in the correct order.

feat: add provisioing script

---

frontend/app/ui/subscriptions/confirm/controller.js
frontend/app/ui/subscriptions/reload/controller.js
frontend/translations/de.yaml
frontend/translations/en.yaml

Some actions should avoid being executed by accident.

feat(frontend): add confirm dialogs to actions

---

Makefile
provisioning/init.sh

* Removes the x option (print commands)
* Adds the f and n flags for the symlink
* Adds a new command to the Makefile (init)
* Updates the frontend deployment command

fix: minor fixes and tweaks to the provisioning process

---

.github/workflows/test.yml

I will add the backend tests to this workflow but don't want to
potentially debug two parallel workflows.

feat: add GitHub Actions for frontend testing

---

frontend/app/ui/account/login/template.hbs

All the people I talked to were skeptical that this feature works.

feat(frontend): hide reset link until tested

---

backend/Dockerfile
backend/package.json
frontend/Dockerfile
frontend/nginx.conf

* The backend is a normal Node.js build.
* The frontend is a multi-stage build with NGINX server.

feat: add Dockerfile for backend and frontend

---

README.md

There was not much information before.

chore: update read-me

---

frontend/app/ui/subscriptions/detail/controller.js

fix(frontend): fix missing parameter when paging

---

frontend/app/ui/subscriptions/confirm/controller.js

Using days for the duration can be confusing.

feat(frontend): limit duration unit to hours

---

backend/.gitignore
backend/package.json
backend/yarn.lock

Not used anymore but leads to security alerts by dependabot.

feat(backend): remove NYC/Istanbul dependency

---

backend/package.json
backend/yarn.lock

Not used anymore but leads to security alerts by dependabot.

feat(backend): remove SyRCP dependency

---

frontend/app/services/account.js

This allows to pass a regex through the ENV var which is then used to test against the group name.

fix(permissions): allow dynamic group names

---

frontend/app/index/route.js
frontend/translations/en.yaml

Update according to https://www.adfinis.com/en/contact/

fix(locations): update contact details

---

frontend/app/subscriptions/reload/template.hbs

Customers can have individual prices

fix(subscriptions/reload): remove package price

---

frontend/app/info/controller.js
frontend/app/info/route.js
frontend/app/info/template.hbs
frontend/app/router.js
frontend/tests/unit/info/controller-test.js
frontend/tests/unit/info/route-test.js
frontend/translations/de.yaml
frontend/translations/en.yaml

This page will be used to redirect and inform users about the new
customer-center.

feat: info page

---

frontend/app/services/timed.js
frontend/app/subscriptions/reload/route.js

fix(packages): use `store.query` instead of `store.findAll` to filter by billing type`

---

frontend/translations/de.yaml

Just a small typo fix, nothing special

fix(translations): switch to german formal personal pronoun

---

frontend/app/subscriptions/list/controller.js
frontend/translations/de.yaml
frontend/translations/en.yaml

Extract the number of the cost center from its name and display it
in a separate column.

fix(export): split cost center name

---

.github/workflows/release-container-image.yaml

fix imageref
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>

fix(ghcr): references

---

frontend/translations/de.yaml
frontend/translations/en.yaml

Add missing translation.
Maybe a CI check to scan for missing translations would be beneficial.

fix(translations): add translations for page.subscriptions.own.empty

---

frontend/config/environment.js

I'll update the [secret](https://github.com/adfinis/customer-center/settings/secrets/actions) as well!

fix: fix admin group name
